title: Hello, world! I'm Ignacio Alvarez
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ignacio Alvarez # add your name
author-img: ignacio.jpg # add your photo
about-author:       <p>I am a  developer focusing on back-end development. Always hungry to keep learning.</p> <p>Desarrollador especializado en back-end. Buscando nuevos retos y siempre aprendiendo</p> # add description
social-twitter: Nacho_Alvarez94 # add your Twitter handle

social-github: nachoalvarez94 # add your Github handle
social-linkedin: ignacio-alvarez-iglesias-241888123 # add your Linkedin handle
social-email: alvarez.iglesias.ignacio@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
